packages:
  - 'libs/*'
  - 'apps/web-client'

allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  ngrok: true
  prisma: true
  protobufjs: true
  sharp: false
  unrs-resolver: false
